add pagination to delivery info endpoint
com-obj/notiflow pull request #13
Opened 2022-07-05 02:09 UTC by raminismayilov

Here's how the response to a request with the query parameters 'page=2&size=20' looks like:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/55783954/177234483-b8002dc9-4608-4197-a6ae-71c46d2ebabc.png">

Pagination is one-indexed, and is implemented using Spring's own resources (PageImpl, Page, Pageable). I extended PageImpl to minimize what Spring serializes as part of its Page object and to establish one-based indexing.

And here's how a serialized message looks  like:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/55783954/177234703-527f65fa-7b57-411f-bd97-15f30425121a.png">

It's the serialized form of a MessageContent object, from which various content types (EmailContent, SmsContent, etc) inherit. So if the message is an email, we'll see an email-specific content structure.

I tried to keep my changes as minimal and less intrusive as possible to not cause extensive breaks in tests and elsewhere. Tests required slight modifications to get them back to normal.

2022-07-05 03:30 UTC, cuzyjan requested changes
its just fine apart of that one comment.
I'm thinking if it would make sence to test the pagination by it self.. which means test with page size 1 somethinkg that return at least two delivery infors and try first page and second page.
... BTW: does ReusltPage object has these indication if the FE can fetch next page? - Now i see in you description above: It has

2022-07-05 03:30 UTC, cuzyjan commented on src/main/java/com/obj/nc/repositories/DeliveryInfoRepository.java
> +    String QRY_LATEST_DELIVERY_INFO_BY_ENDPOINT_ID = "WITH temp AS (\n" +
kind of copy/paste this sql and the secong. 
+ 'temp' is not very descriptive name.. would suggest to name the temprary teble/view more related to what it contains

2022-07-05 03:37 UTC, cuzyjan commented
I'm thinking about the @class attribute in the message part of our responce.. It is completely ok to have it like this in NC it self but I'm not sure if it is ok to put it into an interface that is used by external systems. It would be better to have somethink more like @Type in the Enpoint class.
This brings me to a second thought. Should we expose our domain entities to the outside world directly like we do? Wouldn't it be sage to have in this case for both Endpoint and MessageBody (in message attribute) a dedicated DTO? hmm... most likely would, the question is if it is worth the efford

2022-07-07 09:29 UTC, raminismayilov commented
After adding DTOs, here's how the response from that specific endpoint looks like:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/55783954/177741043-982e3433-995e-4961-a8fa-aa7a8bd66bed.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/55783954/177741183-acec0070-9a32-411c-a962-01f798b19d3a.png">

2022-07-07 10:08 UTC, cuzyjan commented
I think the new format is very nice. We got rid of those @, we are internally typ safe, it all seems "object oriented",.. 
Fine for me

2022-07-07 10:30 UTC, raminismayilov commented
Filled those missing toDto() methods.

2022-07-07 10:32 UTC, cuzyjan approved these changes

2022-07-11 13:10 UTC, merged